name: Go

on:
  pull_request:
    paths-ignore:
      - "images/**"
      - "**/*.md"
    branches:
      - main
  push:
    paths-ignore:
      - "images/**"
      - "**/*.md"
    branches:
      - main

jobs:
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: "latest"
          args: -c ./golangci.yml
      - name: Format lint
        run: |
          make install-tools && make format && git diff --quiet
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          [
            "1.16.x",
            "1.17.x",
            "1.18.x",
            "1.19.x",
          ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go}}
      - name: Run Tests
        run: make test
